apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-three
  namespace: argocd
spec:
  project: default

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: dev
  destination: 
    server: {{ .Values.spec.destination.server }}
    namespace: app-3

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
